require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"

  DisplayCopNames: true
  TargetRubyVersion: '3.2.2'

Metrics/BlockLength:
  Exclude:
    - "lib/tasks/auto_annotate_models.rake"
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
